---

- include: mysql.yml

- name: Check if systemd is installed
  command: dpkg -L systemd
  register: dpkg_systemd_check
  ignore_errors: yes

- include: systemd.yml
  when: dpkg_systemd_check.rc == 0

- name: Check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes

- include: munin-plugin.yml
  when: dpkg_munin_node_check.rc == 0

- name: Check if fail2ban is installed
  command: dpkg -L fail2ban
  register: dpkg_fail2ban_check
  ignore_errors: yes

- include: fail2ban-jail.yml
  when: dpkg_fail2ban_check.rc == 0