---

- name: reload_systemd
  command: systemctl daemon-reload
  become: yes

- name: restart_mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
  become: yes

- name: restart_munin_node
  service:
    name: munin-node
    state: restarted
  become: yes

- name: restart_fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes

- name: mysql_restart_zabbix_agent
  service:
    name: zabbix-agent
    state: restarted
  become: yes
